"""Removed path

Revision ID: 1fff261d079a
Revises: f49e146a50c5
Create Date: 2024-04-09 16:00:43.417956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fff261d079a'
down_revision = 'f49e146a50c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_index('ix_image_path')
        batch_op.drop_column('path')

    with op.batch_alter_table('volume', schema=None) as batch_op:
        batch_op.drop_index('ix_volume_path')
        batch_op.drop_column('path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.VARCHAR(length=255), nullable=False))
        batch_op.create_index('ix_volume_path', ['path'], unique=1)

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.VARCHAR(length=255), nullable=False))
        batch_op.create_index('ix_image_path', ['path'], unique=1)

    # ### end Alembic commands ###
