"""changed image

Revision ID: 318029ffac08
Revises: 55d7e34332b9
Create Date: 2024-04-11 22:23:36.256802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318029ffac08'
down_revision = '55d7e34332b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_index('ix_image_version')
        batch_op.drop_column('version')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), nullable=False))
        batch_op.create_index('ix_image_version', ['version'], unique=False)

    # ### end Alembic commands ###
