"""I dont know

Revision ID: 55d7e34332b9
Revises: 12768d1ddef9
Create Date: 2024-04-11 15:48:57.892406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55d7e34332b9'
down_revision = '12768d1ddef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_index('ix_image_docker_id')
        batch_op.create_index(batch_op.f('ix_image_docker_id'), ['docker_id'], unique=True)
        batch_op.drop_index('ix_image_name')
        batch_op.create_index(batch_op.f('ix_image_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_name'))
        batch_op.create_index('ix_image_name', ['name'], unique=False)
        batch_op.drop_index(batch_op.f('ix_image_docker_id'))
        batch_op.create_index('ix_image_docker_id', ['docker_id'], unique=False)

    # ### end Alembic commands ###
