"""volumes table

Revision ID: 5bdab5824295
Revises: 
Create Date: 2024-04-08 15:23:59.342519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bdab5824295'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('volume', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volume_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_volume_path'), ['path'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volume', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volume_path'))
        batch_op.drop_index(batch_op.f('ix_volume_name'))

    op.drop_table('volume')
    # ### end Alembic commands ###
