"""changed image to contain docker_id

Revision ID: dc97e6153938
Revises: 1fff261d079a
Create Date: 2024-04-11 10:27:26.585891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc97e6153938'
down_revision = '1fff261d079a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('docker_id', sa.String(length=255), nullable=False))
        batch_op.create_index(batch_op.f('ix_image_docker_id'), ['docker_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_docker_id'))
        batch_op.drop_column('docker_id')

    # ### end Alembic commands ###
